catch non-existent files

diff --git a/supported/doom b/supported/doom
--- a/supported/doom
+++ b/supported/doom
@@ -52,6 +52,10 @@ fi
 go() {
 	verify_args "$@"
 	WADFILE=`unravel "$1"`
+    if [ ! -f "$WADFILE" ]; then
+        echo "ERROR: '$WADFILE' does not exist." >&2
+        exit
+    fi
 	MD5SUM=`checksum "$WADFILE"`
 	debug "WADFILE=$WADFILE"
 	check_for_v19
diff --git a/supported/doom2 b/supported/doom2
--- a/supported/doom2
+++ b/supported/doom2
@@ -49,9 +49,14 @@ fi
 go() {
 	verify_args "$@"
 	WADFILE=`unravel "$1"`
+    if [ ! -f "$WADFILE" ]; then
+        echo "ERROR: '$WADFILE' does not exist." >&2
+        exit
+    fi
 	MD5SUM=`checksum "$WADFILE"`
-	check_for_v19
 	debug "WADFILE=$WADFILE"
+	check_for_v19
+
 	DEST=`echo $DATADIR | sed 's,^/,,'`/doom2.wad
 
 	if [ "" = "$OUTDIR" ]; then
