more file perm checking for zipfile

diff --git a/supported/rott b/supported/rott
--- a/supported/rott
+++ b/supported/rott
@@ -68,7 +68,9 @@ DEB="$DATADIR/$DEBBASE"
 go() {
 	verify_args "$@"
 	ZIPFILE=`unravel "$rottzip"`
-    [ -f "$ZIPFILE" ] || die "ERROR: '$ZIPFILE' does not exist."
+    [ -e "$ZIPFILE" ] || die "ERROR: '$ZIPFILE' does not exist."
+    [ -f "$ZIPFILE" ] || die "ERROR: '$ZIPFILE' is not a file."
+    [ -r "$ZIPFILE" ] || die "ERROR: '$ZIPFILE' cannot be read."
 	checksum "$ZIPFILE"
 	if [ "$CHECKSUM" != "$ZIPSUM" ]; then
 		echo "warning: checksum is not what we expected" >&2
